spring:
  zipkin:
    base-url: http://47.107.120.53:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ENVIRONMENT-CONFIGURATION-CENTER
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://47.107.120.53:8761/eureka/