spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangspx/spring-cloud-config-repo
          username:
          password:
          search-paths: /*
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/